import{a as f,S as p,i as n}from"./assets/vendor-BGz2EIcA.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const L=e=>`
  <li class="gallery-card">
  <a href="${e.largeImageURL}">
  <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" />
  </a>
  <ul class="comments">
  <li class="com">likes: ${e.likes}</li>
  <li class="com">views: ${e.views}</li>
  <li class="com">comments: ${e.comments}</li>
  <li class="com">downloads: ${e.downloads}</li>
  </ul>
  </li>
  `,w=(e,r,o)=>{const a=e.map(L).join("");r.innerHTML=a,o.refresh()},b="https://pixabay.com/api/",v="45481518-557ec69fe97012c17356df52c",y=async(e,r)=>{const o={params:{q:e,orientation:"horizontal",per_page:20,key:v,image_type:"photo",safesearch:!0,page:r,per_page:15}},{data:a}=await f.get(`${b}`,o);return a};let i=1,l="";const h=document.querySelector(".js-search-form"),m=document.querySelector(".js-gallery"),c=document.querySelector(".more-button"),d=document.querySelector(".js-loader"),g=new p(".gallery-card a");h.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements.user_query.value.trim(),!!l){i=1,c.classList.add("more-button-hidden"),m.innerHTML="",d.classList.remove("loader-hidden");try{const r=await y(l,i);if(r.hits.length===0){n.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again.",position:"topLeft"}),h.reset();return}w(r.hits,m,g),r.totalHits>15&&c.classList.remove("more-button-hidden")}catch{n.error({title:"Error",message:"Something went wrong. Please, try again later."})}finally{d.classList.add("loader-hidden")}}});c.addEventListener("click",async()=>{i+=1,d.classList.remove("loader-hidden");try{const e=await y(l,i);if(e.hits.length===0||i*15>=e.totalHits){n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}),c.classList.add("more-button-hidden");return}const r=e.hits.map(createGalleryCard).join("");m.insertAdjacentHTML("beforeend",r),g.refresh();const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}catch{n.error({title:"Error",message:"Something went wrong. Please, try again later."})}finally{d.classList.add("loader-hidden")}});
//# sourceMappingURL=index.js.map
