import{a as L,S as w,i}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const f=e=>`
  <li class="gallery-card">
  <a href="${e.largeImageURL}">
  <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" />
  </a>
  <ul class="comments">
  <li class="com">likes: ${e.likes}</li>
  <li class="com">views: ${e.views}</li>
  <li class="com">comments: ${e.comments}</li>
  <li class="com">downloads: ${e.downloads}</li>
  </ul>
  </li>
  `,b="https://pixabay.com/api/",S="45481518-557ec69fe97012c17356df52c",y=async(e,r)=>{const s={params:{q:e,orientation:"horizontal",per_page:20,key:S,image_type:"photo",safesearch:!0,page:r,per_page:15}},{data:a}=await L.get(`${b}`,s);return a},u=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),d=document.querySelector(".js-loader"),h=document.querySelector(".more-button");let l=1,n="";const g=new w(".js-gallery a",{captiondata:"alt",captionDelay:250}),v=async e=>{if(e.preventDefault(),n=u.elements.user_query.value.trim(),n===""){i.error({title:"Error",message:"Please fill out the form",position:"topRight",timeout:3e3});return}l=1,d.classList.remove("loader-hidden");try{const r=await y(n,l);if(r.hits.length===0){i.warning({title:"No results",message:"Sorry, there are no images your search query. Please try again.",position:"topLeft"}),c.innerHTML="";return}const s=r.hits.map(a=>f(a)).join("");c.innerHTML=s,p(),g.refresh(),u.reset(),r.totalHits>15&&h.classList.remove("more-button-hidden")}catch{i.error({title:"Error",message:"Something wrong. Please, try later"})}finally{d.classList.add("loader-hidden")}},P=async()=>{l++,d.classList.remove("loader-hidden");try{const e=await y(n,l),r=e.hits.map(s=>f(s)).join("");c.insertAdjacentHTML("beforeend",r),p(),g.refresh(),Math.ceil(e.totalHits/15)===l&&(h.classList.add("more-button-hidden"),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({title:"Error",message:"Something wrong. Please, try later"})}finally{d.classList.add("loader-hidden")}},p=()=>{const{height:e}=c.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};h.addEventListener("click",P);u.addEventListener("submit",v);
//# sourceMappingURL=index.js.map
