import{a as p,S as L,i}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const f=e=>`
  <li class="gallery-card">
  <a href="${e.largeImageURL}">
  <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" />
  </a>
  <ul class="comments">
  <li class="com">likes: ${e.likes}</li>
  <li class="com">views: ${e.views}</li>
  <li class="com">comments: ${e.comments}</li>
  <li class="com">downloads: ${e.downloads}</li>
  </ul>
  </li>
  `,b="https://pixabay.com/api/",w="45481518-557ec69fe97012c17356df52c",y=async(e,r)=>{const o={params:{q:e,orientation:"horizontal",per_page:20,key:w,image_type:"photo",safesearch:!0,page:r,per_page:15}},{data:a}=await p.get(`${b}`,o);return a},h=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),d=document.querySelector(".js-loader"),m=document.querySelector(".more-button");let l=1,n="";const g=new L(".js-gallery a",{captiondata:"alt",captionDelay:250}),S=async e=>{if(e.preventDefault(),n=h.elements.user_query.value.trim(),n===""){i.error({title:"Error",message:"Please fill out the form",position:"topRight",timeout:3e3});return}l=1,d.classList.remove("loader-hidden");try{const r=await y(n,l);if(r.hits.length===0){i.warning({title:"No results",message:"Sorry, there are no images your search query. Please try again.",position:"topLeft"}),c.innerHTML="",m.classList.add("more-button-hidden");return}const o=r.hits.map(a=>f(a)).join("");c.innerHTML=o,g.refresh(),h.reset(),r.totalHits>15&&m.classList.remove("more-button-hidden")}catch{i.error({title:"Error",message:"Something wrong. Please, try later"})}finally{d.classList.add("loader-hidden")}},v=async()=>{l++,d.classList.remove("loader-hidden");try{const e=await y(n,l),r=e.hits.map(o=>f(o)).join("");c.insertAdjacentHTML("beforeend",r),P(),g.refresh(),Math.ceil(e.totalHits/15)===l&&(m.classList.add("more-button-hidden"),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({title:"Error",message:"Something wrong. Please, try later"})}finally{d.classList.add("loader-hidden")}},P=()=>{const{height:e}=c.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};m.addEventListener("click",v);h.addEventListener("submit",S);
//# sourceMappingURL=index.js.map
